# Generated by Django 4.1.7 on 2023-03-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='Location',
        ),
    ]
