# Generated by Django 4.1.7 on 2023-03-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoryapp', '0002_remove_categorydb_address_remove_categorydb_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='Gender',
            new_name='Books',
        ),
        migrations.RemoveField(
            model_name='categorydb',
            name='Mobile',
        ),
    ]
