# Generated by Django 4.1.7 on 2023-03-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoryapp', '0003_rename_gender_categorydb_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Books',
        ),
    ]
